import { useEffect, useMemo, useState } from 'react'
import { listLearningReusePreferences, saveLearningReusePreference, saveRunbookReflection, setRunbookStatus } from '../lib/campaignRunbook'
import { evidenceBackedStageCount } from '../lib/campaignMomentum'

export default function PortfolioLearningReview({ workspaceId, userId, items = [], onOpenCampaign, onChanged }) {
  const [preferences, setPreferences] = useState([])
  const [focusDrafts, setFocusDrafts] = useState({})
  const [selectedStatementId, setSelectedStatementId] = useState('')
  const [reviewDraft, setReviewDraft] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState('')
  useEffect(() => { listLearningReusePreferences({ workspaceId, userId }).then(setPreferences).catch(() => setPreferences([])) }, [workspaceId, userId])
  const statements = useMemo(() => items.flatMap(item => (item.learningStatements || []).filter(statement => statement.what_changed && statement.evidence_summary && statement.next_action).map(statement => ({ ...statement, sourceItem:item }))), [items])
  const currentStatement = statements.find(statement => statement.id === selectedStatementId)
  const saveFocus = async item => {
    if (!item.runbook) return
    setBusy(`focus-${item.product.id}`); setNotice('')
    try { await setRunbookStatus({ runbook:item.runbook, status:item.runbook.status === 'archived' ? 'active' : item.runbook.status, chosenFocus:focusDrafts[item.product.id] || '' }); setNotice(`Focus saved for ${item.product.name}.`); await onChanged?.() }
    catch (error) { setNotice(error.message || 'Could not save this focus.') }
    finally { setBusy('') }
  }
  const savePortfolioReview = async () => {
    if (!currentStatement?.sourceItem?.runbook || !reviewDraft.trim()) { setNotice('Choose a verified learning and write the cross-portfolio consideration first.'); return }
    setBusy('portfolio-review'); setNotice('')
    try { await saveRunbookReflection({ runbookId:currentStatement.sourceItem.runbook.id, userId, kind:'learning', prompt:'Portfolio Review: What did you learn that another product should consider?', response:reviewDraft }); setNotice('Portfolio Review saved with the source learning. It has not changed any other product.'); setReviewDraft(''); await onChanged?.() }
    catch (error) { setNotice(error.message || 'Could not save the Portfolio Review.') }
    finally { setBusy('') }
  }
  const dismissSuggestion = async (targetItem, statement) => {
    setBusy(`dismiss-${targetItem.product.id}-${statement.id}`); setNotice('')
    try { const saved = await saveLearningReusePreference({ workspaceId, userId, targetProductId:targetItem.product.id, sourceLearningStatementId:statement.id, status:'dismissed' }); setPreferences(current => [...current.filter(item => !(item.target_product_id === saved.target_product_id && item.source_learning_statement_id === saved.source_learning_statement_id)), saved]); setNotice('Suggestion dismissed for this product. It has not changed the source learning.') }
    catch (error) { setNotice(error.message || 'Could not dismiss that suggestion.') }
    finally { setBusy('') }
  }
  const isDismissed = (targetProductId, statementId) => preferences.some(preference => preference.target_product_id === targetProductId && preference.source_learning_statement_id === statementId && ['dismissed', 'disabled'].includes(preference.status))

  return <section className="studio-panel flo-dark-surface" style={{ marginTop:20, padding:20, borderColor:'rgba(190,184,255,.28)' }}><div className="studio-kicker" style={{ color:'#d1ccff' }}>PORTFOLIO LEARNING REVIEW / PRIVATE</div><h2 style={{ color:'#fff', fontSize:22, letterSpacing:'-.05em', marginTop:6 }}>Choose what deserves the next meaningful action.</h2><p style={{ color:'rgba(241,242,255,.65)', fontSize:11.5, lineHeight:1.6, marginTop:6, maxWidth:820 }}>This is not a leaderboard. Every app shows only its own Runbook evidence, current focus, and linked learning. Cross-product suggestions are transparent drafts that remain optional.</p>
    <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))', gap:10, marginTop:15 }}>{items.map(item => { const count = evidenceBackedStageCount(item.checkpoints); return <article key={item.product.id} style={{ padding:13, borderRadius:11, background:'rgba(255,255,255,.035)', border:'1px solid rgba(255,255,255,.1)' }}><div style={{ display:'flex', justifyContent:'space-between', gap:8, alignItems:'start' }}><div><b style={{ color:'#fff', fontSize:12.5 }}>{item.product.name}</b><div style={{ color:'rgba(241,242,255,.53)', fontSize:9.5, marginTop:4 }}>{item.campaign?.name || 'No campaign yet'}</div></div><span style={{ color:'#d7d2ff', fontSize:9, whiteSpace:'nowrap' }}>{item.checkpoints.length ? count.label : 'No Runbook'}</span></div><p style={{ color:'rgba(241,242,255,.68)', fontSize:10, lineHeight:1.5, marginTop:9 }}><b style={{ color:'#eceaff' }}>Next:</b> {item.nextAction?.label}</p><p style={{ color:'rgba(241,242,255,.48)', fontSize:9.5, marginTop:5 }}>{item.lastVerifiedLearningAt ? `Last verified learning: ${new Date(item.lastVerifiedLearningAt).toLocaleDateString()}` : 'No verified learning recorded yet.'}</p>{item.runbook && <div style={{ display:'grid', gap:6, marginTop:10 }}><input value={focusDrafts[item.product.id] ?? item.runbook.chosen_focus ?? ''} onChange={event => setFocusDrafts(current => ({ ...current, [item.product.id]:event.target.value }))} placeholder="Set an owner-selected focus" style={{ width:'100%', boxSizing:'border-box', background:'rgba(0,0,0,.22)', border:'1px solid rgba(255,255,255,.15)', borderRadius:7, color:'#fff', padding:'7px 8px', font:'inherit', fontSize:9.5 }}/><div style={{ display:'flex', gap:6 }}><button onClick={() => saveFocus(item)} disabled={busy === `focus-${item.product.id}`} className="studio-chip" style={{ color:'#e9e6ff', borderColor:'rgba(214,209,255,.25)', fontSize:8.5 }}>Set focus</button><button onClick={() => onOpenCampaign?.(item)} className="studio-chip" style={{ color:'#e9e6ff', borderColor:'rgba(214,209,255,.25)', fontSize:8.5 }}>Open runbook</button></div></div>}{!item.runbook && <button onClick={() => onOpenCampaign?.(item)} className="studio-chip" style={{ marginTop:10, color:'#e9e6ff', borderColor:'rgba(214,209,255,.25)', fontSize:8.5 }}>Start campaign</button>}</article> })}</div>
    <div style={{ marginTop:16, paddingTop:15, borderTop:'1px solid rgba(255,255,255,.1)' }}><div className="studio-kicker" style={{ color:'#d1ccff' }}>OPTIONAL PORTFOLIO REVIEW</div><p style={{ color:'rgba(241,242,255,.63)', fontSize:10.5, marginTop:5 }}>What did you learn that another product should consider?</p><div style={{ display:'grid', gridTemplateColumns:'minmax(220px,.45fr) minmax(0,1fr) auto', gap:8, marginTop:9 }}><select value={selectedStatementId} onChange={event => { const next = statements.find(statement => statement.id === event.target.value); setSelectedStatementId(event.target.value); setReviewDraft(next ? `${next.what_changed}\n\n${next.evidence_summary}\n\nConsider: ${next.next_action}` : '') }} style={{ background:'rgba(0,0,0,.22)', border:'1px solid rgba(255,255,255,.15)', borderRadius:7, color:'#fff', padding:'8px', font:'inherit', fontSize:9.5 }}><option value="">Choose verified learning</option>{statements.map(statement => <option key={statement.id} value={statement.id}>{statement.sourceItem.product.name} · {statement.next_action.slice(0, 55)}</option>)}</select><textarea rows={3} value={reviewDraft} onChange={event => setReviewDraft(event.target.value)} placeholder="Copy as a draft, edit it for context, or leave it unsaved." style={{ width:'100%', boxSizing:'border-box', background:'rgba(0,0,0,.22)', border:'1px solid rgba(255,255,255,.15)', borderRadius:7, color:'#fff', padding:'8px', font:'inherit', fontSize:9.5, resize:'vertical' }}/><button onClick={savePortfolioReview} disabled={busy === 'portfolio-review'} className="studio-button" style={{ alignSelf:'start', padding:'8px 10px', fontSize:9 }}>Save reflection</button></div></div>
    {statements.length > 0 && <div style={{ marginTop:16, paddingTop:15, borderTop:'1px solid rgba(255,255,255,.1)' }}><div className="studio-kicker" style={{ color:'#d1ccff' }}>TRANSPARENT REUSE SUGGESTIONS</div><div style={{ display:'grid', gap:8, marginTop:9 }}>{items.flatMap(target => statements.filter(statement => statement.sourceItem.product.id !== target.product.id && !isDismissed(target.product.id, statement.id)).slice(0, 1).map(statement => <article key={`${target.product.id}-${statement.id}`} style={{ padding:10, borderRadius:9, background:'rgba(255,255,255,.035)', border:'1px solid rgba(255,255,255,.09)' }}><b style={{ color:'#fff', fontSize:10.5 }}>{target.product.name} could consider a source-linked draft from {statement.sourceItem.product.name}.</b><p style={{ color:'rgba(241,242,255,.63)', fontSize:9.5, lineHeight:1.5, marginTop:4 }}><b style={{ color:'#e8e5ff' }}>Source campaign:</b> {statement.sourceItem.campaign?.name || 'Campaign Runbook'} · <b style={{ color:'#e8e5ff' }}>Evidence:</b> {statement.evidence_summary} · <b style={{ color:'#e8e5ff' }}>Why:</b> {statement.next_action}</p><div style={{ display:'flex', gap:6, marginTop:7 }}><button onClick={() => onOpenCampaign?.(target, statement)} className="studio-chip" style={{ color:'#e9e6ff', borderColor:'rgba(214,209,255,.25)', fontSize:8.5 }}>Use as editable draft</button><button onClick={() => dismissSuggestion(target, statement)} disabled={busy === `dismiss-${target.product.id}-${statement.id}`} className="studio-chip" style={{ color:'rgba(241,242,255,.65)', borderColor:'rgba(255,255,255,.15)', fontSize:8.5 }}>Not now</button></div></article>))}</div></div>}
    {notice && <p role="status" style={{ color:'#d9d4ff', fontSize:10, marginTop:11 }}>{notice}</p>}
  </section>
}
