import OpenAI from 'openai';

export const maxDuration = 60;

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/json');

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: 'Missing OPENAI_API_KEY environment variable.' });
    }

    let body = req.body;
    if (typeof body === 'string') {
      try { body = JSON.parse(body); } catch (e) { body = {}; }
    }

    const prompt = (body && body.prompt) || 'Professional commercial product advertising creative';

    const openai = new OpenAI({ apiKey });

    const response = await openai.images.generate({
      model: 'gpt-image-2',
      prompt: prompt,
      n: 1,
      size: '1024x1024',
      quality: 'low',
    });

    const images = response.data.map(d => {
      if (d.url) return d.url;
      if (d.b64_json) return `data:image/png;base64,${d.b64_json}`;
      return null;
    }).filter(Boolean);

    if (!images.length) {
      throw new Error('No image generated by OpenAI.');
    }

    return res.status(200).json({ images });
  } catch (err) {
    console.error('OpenAI generation error:', err);
    return res.status(500).json({ 
      error: err.message || 'Failed to generate image with OpenAI.' 
    });
  }
}
